import { ServerConfig } from './types';

export const DEFAULT_SERVER_CONFIG: ServerConfig = {
  name: "U-bot Community",
  tagline: "The official home and interactive portal for U-bot",
  description: "Welcome to the official U-bot community portal! We are an active hub centered around our customized Discord resident assistant, U-bot. Use this portal to test our funny bot live in chat, view upcoming gaming and dev events, check out our guidelines, or custom design your landing page profile live.",
  inviteLink: "https://discord.com/oauth2/authorize?client_id=1509885542966366319&response_type=code&redirect_uri=https%3A%2F%2F36ef0d5b-7184-44a8-9f07-7ef348a8026b-003s4qhx0gfpmuk.sisko.replit.dev%2Fapi%2Fauth%2Fcallback&scope=dm_channels.messages.read+dm_channels.messages.write",
  memberCount: 3840,
  onlineCount: 1242,
  themeColor: "blurple",
  bannerPreset: "gaming-nebula",
  iconType: "initials",
  iconUrl: "",
  discordGuildId: "631579758778613760", // Default to Vite Community live Server Widget ID for spectacular live feedback
  rules: [
    {
      id: "rule-1",
      number: 1,
      title: "Respectful Communication & Empathy",
      description: "Treat other members with respect and curiosity. Personal attacks, hate speech, bullying, or aggressive behavior will result in an immediate warning or ban."
    },
    {
      id: "rule-2",
      number: 2,
      title: "No Spam or Excessive Flooding",
      description: "Keep messages relevant to designated channels. Do not spam links, emojis, code blocks, or images. Avoid unsolicited direct messaging or tag-spoofing staff."
    },
    {
      id: "rule-3",
      number: 3,
      title: "No Inappropriate or NSFW Material",
      description: "This is a safe-for-work community. Do not upload, post, or link to sexually explicit materials, extreme violence, or harmful software."
    },
    {
      id: "rule-4",
      number: 4,
      title: "Constructive Self-Promotion only",
      description: "Unsolicited cold-messaging, server invitation dumping, or advertising of paid services in general chat is strictly forbidden. Use the #projects-showcase channel respectfully."
    },
    {
      id: "rule-5",
      number: 5,
      title: "U-bot Immunity & Exemption Decree",
      description: "Any lazy, sleepy, or unhelpful response generated by the chief assistant U-bot in chat is exempt from protocol criticism. Do not tag staff when U-bot refuses to do your math homework or crashes after 10 seconds of action."
    }
  ],
  events: [
    {
      id: "event-1",
      title: "💡 Dev Co-working Session",
      date: "Every Monday & Wednesday",
      time: "18:00 UTC",
      location: "🔊 Lounge Voip Channel",
      description: "Join our quiet co-working circle! Share your screen, chat about what you're building, bounce technical hurdles off fellow developers, or code in friendly company.",
      attendeeCount: 18
    },
    {
      id: "event-2",
      title: "🎮 Among Us & Gartic Phone Night",
      date: "Friday, June 5th",
      time: "20:00 UTC",
      location: "🔊 Game Lounge Chat",
      description: "Unwind for the weekend! We're playing high-suspicion multiplayer party games. Beginners are absolutely welcome—simply hop on the mic and get ready to laugh.",
      attendeeCount: 24
    },
    {
      id: "event-3",
      title: "🎤 Technical Career Q&A Grid",
      date: "Sunday, June 14th",
      time: "15:00 UTC",
      location: "🔊 Stage Room",
      description: "A relaxed fire-chat session featuring staff and senior community engineers discussing cloud design patterns, system design interview mastery, and career growth.",
      attendeeCount: 42
    }
  ],
  staff: [
    {
      id: "staff-1",
      username: "Aura",
      discriminator: "1010",
      roleName: "Owner & Creator",
      roleColor: "#F472B6", // pink-400
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
      status: "online",
      customStatus: "🚀 Polishing the new web portal core!"
    },
    {
      id: "staff-2",
      username: "Teko",
      discriminator: "4040",
      roleName: "Developer Moderator",
      roleColor: "#3B82F6", // blue-500
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
      status: "idle",
      customStatus: "💤 AFK - Compiling something heavy"
    },
    {
      id: "staff-3",
      username: "Mee6000",
      discriminator: "9999",
      roleName: "Community Bot",
      roleColor: "#10B981", // emerald-500
      avatarUrl: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&w=150&q=80",
      status: "online",
      customStatus: "🤖 Type '!help' in chat for interactive tools"
    }
  ],
  commands: [
    {
      id: "cmd-ban",
      command: "!ban @user [reason]",
      description: "Permanently bans a member. DMs them before banning.",
      category: "Moderation",
      exampleInput: "!ban @Spammer123 Spreading unsafe connections",
      responseType: "embed",
      embedTitle: "🚨 Member Banned",
      embedColor: "#F23F43",
      embedFields: [
        { label: "Target User", value: "Spammer123#0101" },
        { label: "Moderator", value: "Staff#1010" },
        { label: "Reason", value: "Spreading unsafe connections" }
      ]
    },
    {
      id: "cmd-kick",
      command: "!kick @user [reason]",
      description: "Kicks a member (they can rejoin).",
      category: "Moderation",
      exampleInput: "!kick @TrollUser Incessant mic-spamming",
      responseType: "embed",
      embedTitle: "👟 Member Kicked",
      embedColor: "#F0B232",
      embedFields: [
        { label: "Target User", value: "TrollUser#8080" },
        { label: "Moderator", value: "Staff#1010" },
        { label: "Reason", value: "Incessant mic-spamming" }
      ]
    },
    {
      id: "cmd-mute",
      command: "!mute @user [minutes] [reason]",
      description: "Timeouts a member (default 10 min, max 40320 = 28 days). DMs them.",
      category: "Moderation",
      exampleInput: "!mute @SpamLover 60 Flooding channels",
      responseType: "embed",
      embedTitle: "🔇 Member Timed Out",
      embedColor: "#E91E63",
      embedFields: [
        { label: "Target User", value: "SpamLover#1234" },
        { label: "Duration", value: "60 minutes" },
        { label: "Reason", value: "Flooding channels" }
      ]
    },
    {
      id: "cmd-unmute",
      command: "!unmute @user",
      description: "Removes an active timeout.",
      category: "Moderation",
      exampleInput: "!unmute @SpamLover",
      responseType: "text",
      responseText: "🔊 Successfully removed active timeout for @SpamLover."
    },
    {
      id: "cmd-warn",
      command: "!warn @user [reason]",
      description: "Issues a warning and DMs the member.",
      category: "Moderation",
      exampleInput: "!warn @SpamLover Flooding general chat",
      responseType: "embed",
      embedTitle: "⚠️ Member Warned",
      embedColor: "#F59E0B",
      embedFields: [
        { label: "Target User", value: "SpamLover#1234" },
        { label: "Moderator", value: "Staff#1010" },
        { label: "Reason", value: "Flooding general chat" }
      ]
    },
    {
      id: "cmd-warnings",
      command: "!warnings @user",
      description: "Lists all warnings for a member.",
      category: "Moderation",
      exampleInput: "!warnings @SpamLover",
      responseType: "text",
      responseText: "📋 Active warnings for @SpamLover:\n1. Flooding general chat (Staff#1010) - Today\n2. Caps lock behavior (Teko#4040) - Yesterday"
    },
    {
      id: "cmd-clearwarnings",
      command: "!clearwarnings @user",
      description: "Clears all warnings for a member.",
      category: "Moderation",
      exampleInput: "!clearwarnings @SpamLover",
      responseType: "text",
      responseText: "✅ Cleared all warnings for @SpamLover (Admin override)."
    },
    {
      id: "cmd-purge",
      command: "!purge <1-100>",
      description: "Bulk-deletes that many messages in the channel.",
      category: "Moderation",
      exampleInput: "!purge 50",
      responseType: "text",
      responseText: "🗑️ Bulk deleted 50 messages from #general-chat."
    },
    {
      id: "cmd-slowmode",
      command: "!slowmode <0-21600>",
      description: "Sets channel slowmode in seconds. 0 = off, max = 6 hours.",
      category: "Moderation",
      exampleInput: "!slowmode 10",
      responseType: "text",
      responseText: "⏱️ Slowmode set to 10 seconds in this channel."
    },
    {
      id: "cmd-userinfo",
      command: "!userinfo [@user]",
      description: "Shows join date, account age, roles, warnings, mute status. Omit @user for yourself.",
      category: "Utility",
      exampleInput: "!userinfo @Aura",
      responseType: "embed",
      embedTitle: "🔍 User Information",
      embedColor: "#2196F3",
      embedFields: [
        { label: "Joined Server", value: "Jan 12, 2024" },
        { label: "Account Created", value: "Oct 24, 2019" },
        { label: "Active Roles", value: "Owner, Developer, Staff" },
        { label: "Mute Status", value: "Active (None)" }
      ]
    },
    {
      id: "cmd-help",
      command: "!help",
      description: "Shows all commands.",
      category: "Utility",
      exampleInput: "!help",
      responseType: "text",
      responseText: "🤖 Type !help to review the list of available modules:\n🔨 Moderation\n🔍 Info / Utility\n🎭 Reaction Roles"
    },
    {
      id: "cmd-reactionrole-create",
      command: "!reactionrole create",
      description: "Posts a reaction role panel in the current channel.",
      category: "Reaction Roles",
      exampleInput: "!reactionrole create",
      responseType: "embed",
      embedTitle: "🎭 Select Roles Below",
      embedColor: "#9C27B0",
      embedFields: [
        { label: "Gaming", value: "React with 🎮" },
        { label: "Developer", value: "React with 💻" },
        { label: "Announcements", value: "React with 📢" }
      ]
    },
    {
      id: "cmd-reactionrole-add",
      command: "!reactionrole add <emoji> @role <messageId>",
      description: "Links an emoji+role to a message. Bot auto-reacts to it.",
      category: "Reaction Roles",
      exampleInput: "!reactionrole add 💻 @Developer 12498522384910243",
      responseType: "text",
      responseText: "✅ Added role mapping: 💻 emoji will now grant the @Developer role on message ID: 12498522384910243."
    },
    {
      id: "cmd-reactionrole-list",
      command: "!reactionrole list",
      description: "Shows all active reaction role mappings.",
      category: "Reaction Roles",
      exampleInput: "!reactionrole list",
      responseType: "embed",
      embedTitle: "📋 Active Mappings",
      embedColor: "#9C27B0",
      embedFields: [
        { label: "Message: 124985223849", value: "💻 -> @Developer" },
        { label: "Message: 124985223849", value: "🎮 -> @Gamer" }
      ]
    },
    {
      id: "cmd-reactionrole-remove",
      command: "!reactionrole remove <messageId> <emoji>",
      description: "Removes a mapping.",
      category: "Reaction Roles",
      exampleInput: "!reactionrole remove 124985223849 💻",
      responseType: "text",
      responseText: "✅ Removed role mapping: 💻 on message ID 124985223849."
    }
  ]
};

// Beautiful theme color definitions mapping theme properties to style tokens
export const THEME_PALETTES = {
  blurple: {
    primary: "bg-[#5865F2]",
    primaryHover: "hover:bg-[#4752C4]",
    text: "text-[#5865F2]",
    border: "border-[#5865F2]",
    ring: "focus:ring-[#5865F2]",
    bgLight: "bg-[#5865F2]/10",
    gradient: "from-[#5865F2] to-[#404eed]"
  },
  emerald: {
    primary: "bg-emerald-500",
    primaryHover: "hover:bg-emerald-600",
    text: "text-emerald-400",
    border: "border-emerald-500",
    ring: "focus:ring-emerald-500",
    bgLight: "bg-emerald-500/10",
    gradient: "from-emerald-500 to-teal-600"
  },
  ruby: {
    primary: "bg-rose-500",
    primaryHover: "hover:bg-rose-600",
    text: "text-rose-400",
    border: "border-rose-500",
    ring: "focus:ring-rose-500",
    bgLight: "bg-rose-500/10",
    gradient: "from-rose-500 to-red-600"
  },
  amber: {
    primary: "bg-amber-500",
    primaryHover: "hover:bg-amber-600",
    text: "text-amber-400",
    border: "border-amber-500",
    ring: "focus:ring-amber-500",
    bgLight: "bg-amber-500/10",
    gradient: "from-amber-500 to-orange-500"
  },
  cyan: {
    primary: "bg-cyan-500",
    primaryHover: "hover:bg-cyan-600",
    text: "text-cyan-400",
    border: "border-cyan-500",
    ring: "focus:ring-cyan-500",
    bgLight: "bg-cyan-500/10",
    gradient: "from-cyan-500 to-blue-500"
  },
  fuchsia: {
    primary: "bg-fuchsia-500",
    primaryHover: "hover:bg-fuchsia-600",
    text: "text-fuchsia-400",
    border: "border-fuchsia-500",
    ring: "focus:ring-fuchsia-500",
    bgLight: "bg-fuchsia-500/10",
    gradient: "from-fuchsia-500 to-purple-600"
  }
};

export const BANNER_PRESETS = [
  {
    id: "gaming-nebula",
    name: "Cosmic Nebula",
    url: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "clean-minimal",
    name: "Midnight Tech Gradient",
    url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "cyber-punk",
    name: "Cyber Neon Alley",
    url: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "lofi-cafe",
    name: "Cozy Lofi Study Room",
    url: "https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "minimalist-setup",
    name: "Sleek Workspace Desk",
    url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80"
  }
];
